# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Castro & Barros'
email: contato@castroebarros.net
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre desenvolvimento de sistemas Web com Ruby on Rails.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://www.castroebarros.net" # the base hostname & protocol for your site
twitter_username: castroebarros
github_username:  castroebarros
timezone: America/Fortaleza

# Build settings
markdown: kramdown

gems:
  - jekyll-multiple-languages-plugin

languages: ["en", "pt-br"]
exclude_from_localizations: ["javascript", "images", "css"]
